### PR TITLE
Raised minimum required version of sphinx

### PR DESCRIPTION
**Pull request by s-weigand**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hi @hmaarrfk,
nice that you made `sphinx-copybutton` on conda available too 😄 
There was [an issue on the original repo](https://github.com/executablebooks/sphinx-copybutton/issues/74), which might or might not have something to do with the conda-forge release, but this PR should fix issues with the conda-forge version.
Also I think @choldgraf the creator of `sphinx-copybutton` would be the perfect fit as an additional maintainer, since he knows best what changes with each release. So if both of you are fine with it I would add him as maintainer.

### CODE REVIEW

**Comment by s-weigand** [comment]
@conda-forge-admin, please rerender

**Comment by choldgraf** [comment]
LGTM, thanks! 👍

**Comment by s-weigand** [comment]
@hmaarrfk are you fine with me adding @choldgraf as a maintainer?

**Comment by s-weigand** [comment]
IMHO, this PR should be merged before #8, since it adapts to the changed home and sets the proper minimum version of sphinx.

**Comment by hmaarrfk** [comment]
Sorry for missing this.

I saw #8 and noticed that the build system had changed. Thanks for the update here!

**Pull request merged**
